import{a as d,S as f,i as n}from"./assets/vendor-D8hBcPQM.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const u="52825058-9c2b701d3fa996d89232a6d0f";function m(o){return d("https://pixabay.com/api/",{params:{key:u,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(r=>r.data).catch(r=>{throw console.log(r.message),r})}const c=document.querySelector(".gallery"),h=new f(".gallery a"),l=document.querySelector(".loader");function p(o){if(!o){console.error("Expected array, got:",o);return}const r=[...o].map(t=>`
    <li class="photo-card"> 
    <a href="${t.largeImageURL}">
    <img class="imgs" src="${t.webformatURL}" alt="${t.tags}" />
    </a>
          <div class="info">
          <p class="likes"> <b>Likes</b> ${t.likes}</p>
           <p class="views"> <b>Views</b>${t.views}</p>
            <p class="comments"> <b>Comments</b>${t.comments}</p>
             <p class="downloads"> <b>Downloads</b>${t.downloads}</p>
          </div>
    </li>`).join("");c.innerHTML=r,h.refresh()}function g(o){c.innerHTML=""}function y(){l.classList.remove("hidden")}function b(){l.classList.add("hidden")}const w=document.querySelector(".form");w.addEventListener("submit",L);function L(o){o.preventDefault(),g();const r=o.target.elements["search-text"].value.trim();if(!r){n.warning({message:"Please enter a search term!",position:"topRight",backgroundColor:"#EF4040",messageColor:"#fff",maxWidth:"330px"});return}y(),m(r).then(t=>{t.hits.length===0?(console.log("Empty search detected"),n.error({message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",theme:"light",maxWidth:"330px",color:"white"})):p(t.hits)}).catch(t=>{console.error("Something went wrong"),n.error({message:"Something went wrong",backgroundColor:"#EF4040",messageColor:"#fff",position:"topRight",maxWidth:"330px"})}).finally(()=>{o.target.reset(),b()})}
//# sourceMappingURL=index.js.map
